lib: [
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.a" {"JS_Parser.a"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.cma" {"JS_Parser.cma"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.cmi" {"JS_Parser.cmi"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.cmt" {"JS_Parser.cmt"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.cmti" {"JS_Parser.cmti"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.cmx" {"JS_Parser.cmx"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.cmxa" {"JS_Parser.cmxa"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.cmxs" {"JS_Parser.cmxs"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.ml" {"JS_Parser.ml"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/JS_Parser.mli" {"JS_Parser.mli"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/META" {"META"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/OfFlow.ml" {"OfFlow.ml"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/PrettyPrint.ml" {"PrettyPrint.ml"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/Syntax.ml" {"Syntax.ml"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/dune-package" {"dune-package"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__.cmi" {"jS_Parser__.cmi"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__.cmt" {"jS_Parser__.cmt"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__.cmx" {"jS_Parser__.cmx"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__.ml" {"jS_Parser__.ml"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__OfFlow.cmi" {"jS_Parser__OfFlow.cmi"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__OfFlow.cmt" {"jS_Parser__OfFlow.cmt"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__OfFlow.cmx" {"jS_Parser__OfFlow.cmx"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__PrettyPrint.cmi" {"jS_Parser__PrettyPrint.cmi"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__PrettyPrint.cmt" {"jS_Parser__PrettyPrint.cmt"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__PrettyPrint.cmx" {"jS_Parser__PrettyPrint.cmx"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__Syntax.cmi" {"jS_Parser__Syntax.cmi"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__Syntax.cmt" {"jS_Parser__Syntax.cmt"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/jS_Parser__Syntax.cmx" {"jS_Parser__Syntax.cmx"}
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/lib/JS_Parser/opam" {"opam"}
]
doc: [
  "/Users/sacha/Prog/github/JS_Parser/_esy/default/store/b/js__parser-93276f0d/install/default/doc/JS_Parser/README.md"
]
