var assert = require("../harness/assert").assert;
var Promise = require("../../../js/Promises/Promise").Promise;

(verifyNotEnumerable)(Promise,"prototype");
(verifyNotWritable)(Promise,"prototype");
(verifyNotConfigurable)(Promise,"prototype")((assert).sameValue)(typeof ((Promise).prototype).then,"function");
(verifyNotEnumerable)((Promise).prototype,"then");
(verifyWritable)((Promise).prototype,"then");
(verifyConfigurable)((Promise).prototype,"then")((assert).sameValue)(typeof ((Promise).prototype).catch,"function");
(verifyNotEnumerable)((Promise).prototype,"catch");
(verifyWritable)((Promise).prototype,"catch");
(verifyConfigurable)((Promise).prototype,"catch")((assert).sameValue)(typeof ((Promise).prototype).finally,"function");
(verifyNotEnumerable)((Promise).prototype,"finally");
(verifyWritable)((Promise).prototype,"finally");
(verifyConfigurable)((Promise).prototype,"finally")(verifyProperty)(Promise,"allSettled",{configurable : true; writable : true; enumerable : false})(verifyNotEnumerable)(Promise,"race");
(verifyWritable)(Promise,"race");
(verifyConfigurable)(Promise,"race")var desc = (((Object).getOwnPropertyDescriptor)(Promise,(Symbol).species));
((assert).sameValue)((desc).set,undefined);
((assert).sameValue)(typeof (desc).get,"function");
(verifyNotEnumerable)(Promise,(Symbol).species);
(verifyConfigurable)(Promise,(Symbol).species)(verifyNotEnumerable)(Promise,"reject");
(verifyWritable)(Promise,"reject");
(verifyConfigurable)(Promise,"reject")(verifyNotEnumerable)(Promise,"resolve");
(verifyWritable)(Promise,"resolve");
(verifyConfigurable)(Promise,"resolve")(verifyNotEnumerable)(Promise,"all");
(verifyWritable)(Promise,"all");
(verifyConfigurable)(Promise,"all")(verifyNotEnumerable)(Promise,"prototype");
(verifyNotWritable)(Promise,"prototype");
(verifyNotConfigurable)(Promise,"prototype")((assert).sameValue)(typeof ((Promise).prototype).then,"function");
(verifyNotEnumerable)((Promise).prototype,"then");
(verifyWritable)((Promise).prototype,"then");
(verifyConfigurable)((Promise).prototype,"then")((assert).sameValue)(typeof ((Promise).prototype).catch,"function");
(verifyNotEnumerable)((Promise).prototype,"catch");
(verifyWritable)((Promise).prototype,"catch");
(verifyConfigurable)((Promise).prototype,"catch")((assert).sameValue)(typeof ((Promise).prototype).finally,"function");
(verifyNotEnumerable)((Promise).prototype,"finally");
(verifyWritable)((Promise).prototype,"finally");
(verifyConfigurable)((Promise).prototype,"finally")(verifyProperty)(Promise,"allSettled",{configurable : true; writable : true; enumerable : false})(verifyNotEnumerable)(Promise,"race");
(verifyWritable)(Promise,"race");
(verifyConfigurable)(Promise,"race")var desc = (((Object).getOwnPropertyDescriptor)(Promise,(Symbol).species));
((assert).sameValue)((desc).set,undefined);
((assert).sameValue)(typeof (desc).get,"function");
(verifyNotEnumerable)(Promise,(Symbol).species);
(verifyConfigurable)(Promise,(Symbol).species)