var assert = require("../harness/assert").assert;
var Promise = require("../../../js/Promises/Promise").Promise;

((assert).sameValue)((((Promise).prototype).then).length,2.);
(verifyNotEnumerable)(((Promise).prototype).then,"length");
(verifyNotWritable)(((Promise).prototype).then,"length");
(verifyConfigurable)(((Promise).prototype).then,"length")((assert).sameValue)((((Promise).prototype).catch).length,1.);
(verifyNotEnumerable)(((Promise).prototype).catch,"length");
(verifyNotWritable)(((Promise).prototype).catch,"length");
(verifyConfigurable)(((Promise).prototype).catch,"length")(verifyProperty)(((Promise).prototype).finally,"length",{value : 1.; enumerable : false; configurable : true; writable : false})(verifyProperty)((Promise).allSettled,"length",{configurable : true; writable : false; enumerable : false; value : 1.})((assert).sameValue)(((Promise).race).length,1.);
(verifyNotEnumerable)((Promise).race,"length");
(verifyNotWritable)((Promise).race,"length");
(verifyConfigurable)((Promise).race,"length")((assert).sameValue)((Promise).length,1.);
(verifyNotEnumerable)(Promise,"length");
(verifyNotWritable)(Promise,"length");
(verifyConfigurable)(Promise,"length")((assert).sameValue)(((Promise).reject).length,1.);
(verifyNotEnumerable)((Promise).reject,"length");
(verifyNotWritable)((Promise).reject,"length");
(verifyConfigurable)((Promise).reject,"length")var desc = (((Object).getOwnPropertyDescriptor)(Promise,(Symbol).species));
((assert).sameValue)(((desc).get).length,0.);
(verifyNotEnumerable)((desc).get,"length");
(verifyNotWritable)((desc).get,"length");
(verifyConfigurable)((desc).get,"length")((assert).sameValue)(((Promise).resolve).length,1.);
(verifyNotEnumerable)((Promise).resolve,"length");
(verifyNotWritable)((Promise).resolve,"length");
(verifyConfigurable)((Promise).resolve,"length")((assert).sameValue)(((Promise).all).length,1.);
(verifyNotEnumerable)((Promise).all,"length");
(verifyNotWritable)((Promise).all,"length");
(verifyConfigurable)((Promise).all,"length")((assert).sameValue)((((Promise).prototype).then).length,2.);
(verifyNotEnumerable)(((Promise).prototype).then,"length");
(verifyNotWritable)(((Promise).prototype).then,"length");
(verifyConfigurable)(((Promise).prototype).then,"length")((assert).sameValue)((((Promise).prototype).catch).length,1.);
(verifyNotEnumerable)(((Promise).prototype).catch,"length");
(verifyNotWritable)(((Promise).prototype).catch,"length");
(verifyConfigurable)(((Promise).prototype).catch,"length")(verifyProperty)(((Promise).prototype).finally,"length",{value : 1.; enumerable : false; configurable : true; writable : false})(verifyProperty)((Promise).allSettled,"length",{configurable : true; writable : false; enumerable : false; value : 1.})((assert).sameValue)(((Promise).race).length,1.);
(verifyNotEnumerable)((Promise).race,"length");
(verifyNotWritable)((Promise).race,"length");
(verifyConfigurable)((Promise).race,"length")var desc = (((Object).getOwnPropertyDescriptor)(Promise,(Symbol).species));
((assert).sameValue)(((desc).get).length,0.);
(verifyNotEnumerable)((desc).get,"length");
(verifyNotWritable)((desc).get,"length");
(verifyConfigurable)((desc).get,"length")