var assert = require("../harness/assert").assert;
var Promise = require("../../../js/Promises/Promise").Promise;

((assert).sameValue)((((Promise).prototype).then).name,"then");
(verifyNotEnumerable)(((Promise).prototype).then,"name");
(verifyNotWritable)(((Promise).prototype).then,"name");
(verifyConfigurable)(((Promise).prototype).then,"name")((assert).sameValue)((((Promise).prototype).catch).name,"catch");
(verifyNotEnumerable)(((Promise).prototype).catch,"name");
(verifyNotWritable)(((Promise).prototype).catch,"name");
(verifyConfigurable)(((Promise).prototype).catch,"name")((assert).sameValue)((((Promise).prototype).finally).name,"finally");
(verifyNotEnumerable)(((Promise).prototype).finally,"name");
(verifyNotWritable)(((Promise).prototype).finally,"name");
(verifyConfigurable)(((Promise).prototype).finally,"name")(verifyProperty)((Promise).allSettled,"name",{configurable : true; writable : false; enumerable : false; value : "allSettled"})((assert).sameValue)(((Promise).race).name,"race");
(verifyNotEnumerable)((Promise).race,"name");
(verifyNotWritable)((Promise).race,"name");
(verifyConfigurable)((Promise).race,"name")((assert).sameValue)((Promise).name,"Promise");
(verifyNotEnumerable)(Promise,"name");
(verifyNotWritable)(Promise,"name");
(verifyConfigurable)(Promise,"name")((assert).sameValue)(((Promise).reject).name,"reject");
(verifyNotEnumerable)((Promise).reject,"name");
(verifyNotWritable)((Promise).reject,"name");
(verifyConfigurable)((Promise).reject,"name")((assert).sameValue)(((Promise).resolve).name,"resolve");
(verifyNotEnumerable)((Promise).resolve,"name");
(verifyNotWritable)((Promise).resolve,"name");
(verifyConfigurable)((Promise).resolve,"name")((assert).sameValue)(((Promise).all).name,"all");
(verifyNotEnumerable)((Promise).all,"name");
(verifyNotWritable)((Promise).all,"name");
(verifyConfigurable)((Promise).all,"name")((assert).sameValue)((((Promise).prototype).then).name,"then");
(verifyNotEnumerable)(((Promise).prototype).then,"name");
(verifyNotWritable)(((Promise).prototype).then,"name");
(verifyConfigurable)(((Promise).prototype).then,"name")((assert).sameValue)((((Promise).prototype).catch).name,"catch");
(verifyNotEnumerable)(((Promise).prototype).catch,"name");
(verifyNotWritable)(((Promise).prototype).catch,"name");
(verifyConfigurable)(((Promise).prototype).catch,"name")((assert).sameValue)((((Promise).prototype).finally).name,"finally");
(verifyNotEnumerable)(((Promise).prototype).finally,"name");
(verifyNotWritable)(((Promise).prototype).finally,"name");
(verifyConfigurable)(((Promise).prototype).finally,"name")(verifyProperty)((Promise).allSettled,"name",{configurable : true; writable : false; enumerable : false; value : "allSettled"})((assert).sameValue)(((Promise).race).name,"race");
(verifyNotEnumerable)((Promise).race,"name");
(verifyNotWritable)((Promise).race,"name");
(verifyConfigurable)((Promise).race,"name")